Repository OCA/stock-logistics-shopfloor, pull requests merged in 2025-08, with the labels that each got.

#15 [18.0] shopfloor: fix stock action + improve tests
  shopfloor/actions/stock.py
  shopfloor/tests/test_actions_stock.py
Labels: approved, bot is merging ⏳

#18 [18.0][FIX] shopfloor: fix action `stock.mark_move_line_as_picked`
  shopfloor/actions/stock.py
Labels: bug, bot is merging ⏳

#17 [18.0][MIG] shopfloor: ``delivery`` scenario
  shopfloor/services/cluster_picking.py
  shopfloor/services/delivery.py
  shopfloor/services/zone_picking.py
  shopfloor/tests/__init__.py
  shopfloor/tests/common.py
  shopfloor/tests/test_delivery_base.py
  shopfloor/tests/test_delivery_done.py
  shopfloor/tests/test_delivery_reset_qty_done_line.py
  shopfloor/tests/test_delivery_reset_qty_done_pack.py
  shopfloor/tests/test_delivery_scan_deliver.py
  shopfloor/tests/test_delivery_set_qty_done_line.py
  shopfloor/tests/test_delivery_set_qty_done_pack.py
Labels: bot is merging ⏳

#24 [18.0] shopfloor_mobile: convert readme to *.md
  shopfloor_mobile/README.rst
  shopfloor_mobile/readme/CONTRIBUTORS.md
  shopfloor_mobile/readme/CONTRIBUTORS.rst
  shopfloor_mobile/readme/CREDITS.md
  shopfloor_mobile/readme/CREDITS.rst
  shopfloor_mobile/readme/DESCRIPTION.md
  shopfloor_mobile/readme/DESCRIPTION.rst
  shopfloor_mobile/readme/HISTORY.md
  shopfloor_mobile/readme/ROADMAP.md
  shopfloor_mobile/readme/ROADMAP.rst
  shopfloor_mobile/readme/USAGE.md
  shopfloor_mobile/readme/USAGE.rst
  shopfloor_mobile/static/description/index.html
Labels: bot is merging ⏳

#6 [18.0][MIG]shopfloor_delivery_shipment
  shopfloor_delivery_shipment/README.rst
  shopfloor_delivery_shipment/__init__.py
  shopfloor_delivery_shipment/__manifest__.py
  shopfloor_delivery_shipment/actions/__init__.py
  shopfloor_delivery_shipment/actions/data.py
  shopfloor_delivery_shipment/actions/message.py
  shopfloor_delivery_shipment/actions/schema.py
  shopfloor_delivery_shipment/actions/search.py
  shopfloor_delivery_shipment/data/shopfloor_scenario_data.xml
  shopfloor_delivery_shipment/demo/shopfloor_app_demo.xml
  shopfloor_delivery_shipment/demo/shopfloor_menu_demo.xml
  shopfloor_delivery_shipment/demo/shopfloor_profile_demo.xml
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.plantuml
  shopfloor_delivery_shipment/docs/delivery_shipment_diag_seq.png
  shopfloor_delivery_shipment/docs/oca_logo.png
  shopfloor_delivery_shipment/hooks.py
  shopfloor_delivery_shipment/i18n/es_AR.po
  shopfloor_delivery_shipment/i18n/it.po
  shopfloor_delivery_shipment/i18n/pt_BR.po
  shopfloor_delivery_shipment/i18n/shopfloor_delivery_shipment.pot
  shopfloor_delivery_shipment/models/__init__.py
  shopfloor_delivery_shipment/models/shopfloor_menu.py
  shopfloor_delivery_shipment/pyproject.toml
  shopfloor_delivery_shipment/readme/CONTRIBUTORS.md
  shopfloor_delivery_shipment/readme/CREDITS.md
  shopfloor_delivery_shipment/readme/DESCRIPTION.md
  shopfloor_delivery_shipment/services/__init__.py
  shopfloor_delivery_shipment/services/delivery_shipment.py
  shopfloor_delivery_shipment/static/description/icon.png
  shopfloor_delivery_shipment/static/description/index.html
  shopfloor_delivery_shipment/tests/__init__.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_base.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_loading_list.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_dock.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_location.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_lot.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_package.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_picking.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_scan_document_product.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_unload.py
  shopfloor_delivery_shipment/tests/test_delivery_shipment_validate.py
  shopfloor_delivery_shipment/views/shopfloor_menu.xml
Labels: approved, bot is merging ⏳, ready to merge

#7 [18.0] [MIG] shopfloor_delivery_shipment_mobile
  shopfloor_delivery_shipment_mobile/README.rst
  shopfloor_delivery_shipment_mobile/__init__.py
  shopfloor_delivery_shipment_mobile/__manifest__.py
  shopfloor_delivery_shipment_mobile/i18n/es_AR.po
  shopfloor_delivery_shipment_mobile/i18n/it.po
  shopfloor_delivery_shipment_mobile/i18n/pt_BR.po
  shopfloor_delivery_shipment_mobile/i18n/shopfloor_delivery_shipment_mobile.pot
  shopfloor_delivery_shipment_mobile/pyproject.toml
  shopfloor_delivery_shipment_mobile/readme/CONTRIBUTORS.md
  shopfloor_delivery_shipment_mobile/readme/DESCRIPTION.md
  shopfloor_delivery_shipment_mobile/static/description/icon.png
  shopfloor_delivery_shipment_mobile/static/description/index.html
  shopfloor_delivery_shipment_mobile/static/src/demo/demo.delivery_shipment.esm.js
  shopfloor_delivery_shipment_mobile/static/src/scenario/delivery_shipment.esm.js
  shopfloor_delivery_shipment_mobile/templates/assets.xml
Labels: bot is merging ⏳

#27 [FW][18.0] shopfloor cluster_picking sort lines
  shopfloor/models/shopfloor_menu.py
  shopfloor/services/cluster_picking.py
  shopfloor/tests/test_cluster_picking_sort_order.py
  shopfloor/views/shopfloor_menu.xml
Labels: bot is merging ⏳

#25 [18.0][MIG] shopfloor_reception_mobile
  shopfloor_reception_mobile/README.rst
  shopfloor_reception_mobile/__init__.py
  shopfloor_reception_mobile/__manifest__.py
  shopfloor_reception_mobile/i18n/it.po
  shopfloor_reception_mobile/i18n/shopfloor_reception_mobile.pot
  shopfloor_reception_mobile/pyproject.toml
  shopfloor_reception_mobile/readme/CONTRIBUTORS.md
  shopfloor_reception_mobile/readme/DESCRIPTION.md
  shopfloor_reception_mobile/static/description/icon.png
  shopfloor_reception_mobile/static/description/index.html
  shopfloor_reception_mobile/static/src/demo/demo.reception.esm.js
  shopfloor_reception_mobile/static/src/scenario/reception.esm.js
  shopfloor_reception_mobile/static/src/scenario/reception_states.esm.js
  shopfloor_reception_mobile/templates/assets.xml
Labels: bot is merging ⏳

#32 [18.0][MIG] shopfloor_dangerous_goods_mobile
  shopfloor_dangerous_goods_mobile/README.rst
  shopfloor_dangerous_goods_mobile/__init__.py
  shopfloor_dangerous_goods_mobile/__manifest__.py
  shopfloor_dangerous_goods_mobile/i18n/it.po
  shopfloor_dangerous_goods_mobile/i18n/shopfloor_dangerous_goods_mobile.pot
  shopfloor_dangerous_goods_mobile/pyproject.toml
  shopfloor_dangerous_goods_mobile/readme/CONTRIBUTORS.md
  shopfloor_dangerous_goods_mobile/readme/DESCRIPTION.md
  shopfloor_dangerous_goods_mobile/static/description/icon.png
  shopfloor_dangerous_goods_mobile/static/description/index.html
  shopfloor_dangerous_goods_mobile/static/wms/src/components/picking_select.esm.js
  shopfloor_dangerous_goods_mobile/static/wms/src/css/dangerous_goods.css
  shopfloor_dangerous_goods_mobile/static/wms/src/css/limited_quantity_label.png
  shopfloor_dangerous_goods_mobile/static/wms/src/js/demo/demo.checkout.esm.js
  shopfloor_dangerous_goods_mobile/templates/assets.xml
Labels: bot is merging ⏳

#39 Fix tests
  shopfloor/tests/test_actions_data.py
  shopfloor/tests/test_actions_data_detail.py
  shopfloor_reception/services/reception.py
  shopfloor_reception/tests/test_set_quantity.py
Labels: bot is merging ⏳

#43 [18.0] shopfloor_mobile: fix packaging-qty-picker qty per pkg
  shopfloor_mobile/static/wms/src/components/packaging-qty-picker.esm.js
  shopfloor_mobile/static/wms/src/demo/demo.components.esm.js
  shopfloor_mobile/templates/assets.xml
Labels: approved, bot is merging ⏳

#36 [18.0][IMP] shopfloor_reception_packaging_dimension: collect only needed di…
  shopfloor_reception_packaging_dimension/__manifest__.py
  shopfloor_reception_packaging_dimension/models/__init__.py
  shopfloor_reception_packaging_dimension/models/product_packaging_level.py
  shopfloor_reception_packaging_dimension/services/reception.py
  shopfloor_reception_packaging_dimension/tests/test_set_package_dimension.py
  shopfloor_reception_packaging_dimension/views/product_packaging_level.xml
Labels: bot is merging ⏳
